# Generated by Django 4.2.4 on 2023-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('verification_token', models.CharField(max_length=500)),
                ('timeout', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
