# Generated by Django 4.2.4 on 2023-08-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.salonprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.stylist'),
        ),
    ]
