# Generated by Django 4.2.4 on 2023-08-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adminprofile_user_alter_salonprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_token',
        ),
    ]
