# Generated by Django 4.2.4 on 2023-08-24 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
