# Generated by Django 4.2.4 on 2023-08-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_stylist_created_at_stylist_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Salon approval'), ('approved', 'Approved Stylist change request'), ('rejected', 'Rejected Stylist change request')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylists_requests', to='users.salonprofile')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='users.stylist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_stylist_change_requests',
                'ordering': ['salon', 'created_at'],
            },
        ),
    ]
